catalogo/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	#url(r'^[0-9]{2}', views.diferente, name='diferenete'),
	#url(r'^diferente/', views.diferente, name='diferenete'),
	url(r'^$', views.index, name='index'),
	url(r'^books/$', views.BookListView.as_view(), name='books'),
	url(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
	url(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
	url(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
]

urlpatterns += [   
    url(r'^mybooks/$', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
]

urlpatterns += [   
    url(r'^book/(?P<pk>[-\w]+)/renew/$', views.renew_book_librarian, name='renew-book-librarian'),
]

urlpatterns += [
	url(r'^author/create/$', views.AuthorCreate.as_view(), name='author_create'),
	url(r'^author/(?P<pk>\d+)/update/$', views.AuthorUpdate.as_view(), name='author_update'),
	url(r'^author/(?P<pk>\d+)/delete/$', views.AuthorDelete.as_view(), name='author_delete'),
]

urlpatterns += [
	url(r'^book/create/$', views.BookCreate.as_view(), name='book_create'),
	url(r'^book/(?P<pk>\d+)/update/$', views.BookUpdate.as_view(), name='book_update'),
	url(r'^book/(?P<pk>\d+)/delete/$', views.BookDelete.as_view(), name='book_delete'),
]

localibrary/urls.py
from django.conf.urls import include, url
from django.contrib import admin
#Add URL maps to redirect the base URL to our application
#from django.views.generic import RedirectView
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^catalogo/', include('catalogo.urls')),
    #
    url(r'^prueba/', views.prueba),
    url(r'^$', views.index),
    
    #url(r'^dif/[0-9]{2}', include('catalogo.urls')),
    #url('', RedirectView.as_view(url='/catalogo/', permanent=True)),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

catalogo/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from datetime import date

from django.db import models

# Create your models here.
class Genre(models.Model):
	"""
	Model que representa un género literario (p. ej. ciencia ficción, poesía, etc.).
	"""
	name = models.CharField(max_length=200, help_text="Enter a book genre (e.g Science Fiction, French Poety etc.)")

	def __str__(self):
		"""
		cadena que representa a la instancia particular del modelo (p. ej en el sitio de Administracion)
		"""
		return self.name


from django.urls import reverse #Used to generate URLs by reversing the URL patterns

class Book(models.Model):
	"""
	Modelo que representa un libro (pero no un Ejemplar específico).
	"""
	title = models.CharField(max_length=200)

	author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
	#ForeinKey, ya que un libro tiene un solo autor, pero el mismo autor puede haber escrito muchos libros.
	#'Author' es un string, en vez de un objeto, por que la clase Author aun no ha sido declarada.

	summary = models.TextField(max_length=1009, help_text="Enter a brief description of the book")

	isbn = models.CharField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn"> ISBN numbre</a>') 

	genre = models.ManyToManyField(Genre, help_text="Select a genre for his book")
	# ManyToManyField, porque un género puede contener muchos linros y un libro puede cubrir varios géneros.
	#La clase Genre ya ha sido definida, entonces podemos especificar el objeto arriba.

	def __str__(self):
		"""
		String que representa al objeto Book
		"""
		return self.title

	def get_absolute_url(self):
		"""
		Devuelve elURL a una instacia particular de Book
		"""
		return reverse('book-detail', args=[str(self.id)])

	def display_genre(self):
		"""
        Creates a string for the Genre. This is required to display genre in Admin.
        """
		return ', '.join([ genre.name for genre in self.genre.all()[:3] ])

	display_genre.short_description = 'Genre'
    

import uuid # Requerida para las instancias de libros únicos

class BookInstance(models.Model):
	"""
	Modelo que representa una copia específica de un libro (i.e. 	ue puede ser pewsentado por la biblioteca).
	"""
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="ID único para este libro particular en toda la biblioteca")
	book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
	imprint =models.CharField(max_length=200)
	due_back = models.DateField(null=True, blank=True)

	LOAN_STATUS = (
		('m', 'Maintence'),
		('o', 'On loan'),
		('a', 'Availabe'),
		('r', 'Reserved'),
	)

	status = models.CharField(max_length=1,	choices=LOAN_STATUS, blank=True, default='m', help_text='Disponibilidad del libro')
	borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)


	class Meta:
		ordering = ["due_back"]
		permissions = (("can_mark_returned", "Set book as returned"),) 

	def __str__(self):
		"""
		String para representar el Objeto del Modelo
		"""
		return '%s (%s)' % (self.id,self.book.title)
	@property
	def is_overdue(self):
		if self.due_back and date.today() > self.due_back:
			return True
		return False

class Author(models.Model):
	"""
	Modelo que representa un autor
	"""
	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	date_of_birth = models.DateField(null=True, blank=True)
	date_of_death = models.DateField('died', null=True, blank=True)

	def __str__(self):
		"""
		String para representar el Objeto Modelo
		"""
		#pass
		return '%s, %s' % (self.last_name, self.first_name)

	def get_absolute_url(self):
		"""
		Retorna la url para acceder a una instancia particular de un autor.
		"""
		return reverse('author-detail', args=[str(self.id)])

catalogo/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime #for checking renewal date range.
    
class RenewBookForm(forms.Form):
	renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

	def clean_renewal_date(self):
		data = self.cleaned_data['renewal_date']
		#Check date is not in past. 
		if data < datetime.date.today():
			raise ValidationError(_('Invalid date - renewal in past'))
		#Check date is in range librarian allowed to change (+4 weeks).
		if data > datetime.date.today() + datetime.timedelta(weeks=4):
			raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))
		# Remember to always return the cleaned data. 
		return data

from django.forms import ModelForm
from .models import BookInstance

class RenewBookModelForm(ModelForm):

	def clean_due_back(self):
		data = self.cleaned_data['due_back']
		#check date is not in past.
		if data < datetime.date.today():
			raise ValidationError(_('Invalid date - renewal in past'))

		#Check date in in range libriarian allowed to change (+4 weeks)
		if data > datetime.date.today() + datetime.timedelta(weeks=4):
			raise ValidationError(_('Invalid date - renewal mor than 4 weeks ahead'))

		#Remember to always return the cleaned data.
		return data


	class Meta:
		model = BookInstance
		fields = ['due_back',]
		labels = { ' due_back': _('Renewal date'), }
		help_texts = { 'due_back': _('Enter a date between now and 4 weeks (default 3).'), }

catalogo/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse
from .models import Book, Author, BookInstance, Genre
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
def index(request):
	"""
	Funación vista para la pagina inicio del sitio
	"""
	# Genera contadores de algunos de los objetos principales
	num_books=Book.objects.all().count()
	num_instances=BookInstance.objects.all().count()
	# Libros disponibles (status = 'a')
	num_instances_available=BookInstance.objects.filter(status__exact='a').count()
	num_authors=Author.objects.count() # el 'all()' esta implicito por defecto

	# Number of visits to this view, as counted in the session variable.
	num_visits=request.session.get('num_visits', 0)
	request.session['num_visits'] = num_visits+1

	#Renderiza la plantilla HTML index.html con los datos en la variable contexto
	return render(
		request,
		'index.html',
		context={'num_books':num_books,'num_instances':num_instances,'num_instances_available':num_instances_available,'num_authors':num_authors,'num_visits':num_visits},
	)

def diferente(request):
	return HttpResponse("<h1>esto es como se crean las direfentes ulrs en mismas apps</h1>")

class BookListView(generic.ListView):
	model = Book
	paginate_by = 2

class BookDetailView(generic.DetailView):
	model = Book
	paginate_by = 10

class AuthorListView(generic.ListView):
	model = Author
	paginate_by = 10

class AuthorDetailView(generic.DetailView):
	model = Author

class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
	"""	Generic class-based view listing books on loan to current user."""
	model = BookInstance
	template_name ='catalogo/bookinstance_list_borrowed_user.html'
	paginate_by = 10
	def get_queryset(self):
		return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

from django.contrib.auth.decorators import permission_required

from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
import datetime

from .forms import RenewBookForm
from .forms import RenewBookModelForm


@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
	""" View function for renewing a specific BookInstance by librarian """
	book_inst=get_object_or_404(BookInstance, pk = pk)

	# If this is a POST request then process the Form data
	if request.method == 'POST':

		# Create a form instance and populate it with data from the request (binding):
		#form = RenewBookForm(request.POST)
		form = RenewBookModelForm(request.POST)

		# Check if the form is valid:
		if form.is_valid():
			# process the data in form.cleaned_data as required (here we just write it to the model due_back field)
			#book_inst.due_back = form.cleaned_data['renewal_date']
			book_inst.due_back = form.cleaned_data['due_back']
			book_inst.save()

			# redirect to a new URL:
			#return HttpResponseRedirect(reverse('all-borrowed') )
			return HttpResponseRedirect(reverse('my-borrowed') )

	# If this is a GET (or any other method) create the default form.
	else:
		proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
		#form = RenewBookForm(initial={'renewal_date': proposed_renewal_date,})
		form = RenewBookModelForm(initial={'renewal_date': proposed_renewal_date,})

	return render(request, 'catalogo/book_renew_librarian.html', {'form': form, 'bookinst':book_inst})

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Author

class AuthorCreate(CreateView):
	model  = Author
	fields = '__all__'
	initial={'date_of_death' : '05/01/2018'}

class AuthorUpdate(UpdateView):
	model = Author
	fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']

class AuthorDelete(DeleteView):
	model = Author
	success_url = reverse_lazy('author')

class BookCreate(CreateView):
	model = Book
	fields = '__all__'

class BookUpdate(UpdateView):
	model = Book
	fields = '__all__'

class BookDelete(DeleteView):
	model = Book
	sucess_url = reverse_lazy('book');

catalogo/templates/catalogo/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{author}}?</p>

<form action="" method="POST">
	{% csrf_token %}
	<input type="submit" action="" value="Yes, delete">
</form>

{%  endblock%}

catalogo/templates/catalogo/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
	<h1>Title: {{ author.first_name }}</h1>

{% endblock %}

catalogo/templates/catalogo/author_form.html
{% extends "base_generic.html" %}

{% block content%}

<form action ="" method="post">
	{% csrf_token %}
	<table>
		{{ form.as_table }}
	</table>
	<input type="submit" name="Submit">

</form>
{% endblock %}

catalogo/templates/catalogo/author_list.html
{% extends "base_generic.html" %}

{% block content %}
	<h1>Author List</h1>

	{% if author_list %}
	<ul>
		{% for author in author_list %}
		<li>
			<a href="{{ author.get_absolute_url	}}">{{ author.first_name }}</a>
		</li>
		{% endfor %}
	</ul>
	<ul>
	{% else %}
		<p>There are no Authors in the library.</p>
	</ul>
	{% endif %}
{% endblock %}

catalogo/templates/catalogo/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Book</h1>

<p>Are you sure you want to delete the book: {{author}}?</p>

<form action="" method="POST">
	{% csrf_token %}
	<input type="submit" action="" value="Yes, delete">
</form>

{%  endblock%}

catalogo/templates/catalogo/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
  <p><strong>Language:</strong> {{ book.language }}</p>  
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalogo/templates/catalogo/book_form.html
{% extends "base_generic.html" %}

{% block content%}

<form action ="" method="post">
	{% csrf_token %}
	<table>
		{{ form.as_table }}
	</table>
	<input type="submit" name="Submit">

</form>
{% endblock %}

catalogo/templates/catalogo/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Book List</h1>

    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}       
{% endblock %}

catalogo/templates/catalogo/book_renew_librarian.html
{% extends "base_generic.html" %}
{% block content %}

    <h1>Renew: {{bookinst.book.title}}</h1>
    <p>Borrower: {{bookinst.borrower}}</p>
    <p{% if bookinst.is_overdue %} class="text-danger"{% endif %}>Due date: {{bookinst.due_back}}</p>
    
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

catalogo/templates/catalogo/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
        {% if perms.catalog.can_mark_returned %}<a href="{% url 'renew-book-librarian' bookinst.id %}">Renew {{bookinst.id}}</a>  {% endif %}        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}